# Generated by Django 2.1.7 on 2020-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='head',
            field=models.CharField(max_length=100),
        ),
    ]
