# Generated by Django 3.0.2 on 2020-03-13 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0002_auto_20200311_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('post', models.TextField()),
                ('about_fac', models.TextField()),
                ('email', models.EmailField(max_length=40)),
                ('phone', ckeditor.fields.RichTextField(default='Not provided')),
            ],
        ),
    ]
