# Generated by Django 3.0.2 on 2020-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0004_auto_20200313_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunctfac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('post', models.TextField()),
                ('about_fac', models.TextField()),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
