# Generated by Django 2.0.5 on 2020-03-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0005_adjunctfac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('post', models.TextField()),
                ('about_fac', models.TextField()),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
