# Generated by Django 2.0.5 on 2020-03-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('program', models.CharField(max_length=40)),
                ('rollno', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
