# Generated by Django 2.1.7 on 2020-03-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0008_auto_20200314_2005'),
        ('iiitnweb', '0007_faq'),
    ]

    operations = [
    ]
