# Generated by Django 2.0.5 on 2020-03-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0008_auto_20200314_2005'),
        ('iiitnweb', '0007_faq'),
    ]

    operations = [
    ]
