# Generated by Django 3.0.2 on 2020-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0009_merge_20200314_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
