# Generated by Django 3.0.2 on 2020-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0010_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50)),
                ('prof_name', models.CharField(max_length=50)),
                ('prof_image', models.ImageField(upload_to='static/images/')),
                ('prof_degree', models.CharField(max_length=50)),
                ('prof_interest', models.CharField(max_length=50)),
            ],
        ),
    ]
