# Generated by Django 3.0.2 on 2020-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0011_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='programmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('about_program', models.TextField()),
            ],
        ),
    ]
