# Generated by Django 3.0.2 on 2020-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitnweb', '0012_programmes'),
    ]

    operations = [
        migrations.CreateModel(
            name='convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
    ]
