from django.conf.urls import url

from . import views

urlpatterns = [
		url('', views.home, name='home'),
		url('', views.contact, name='contact'),
		url('', views.Admission.Undergraduate, name='undergraduate'),
		url('', views.Admission.Postgraduate, name='postgraduate'),
		url('', views.Admission.PhD, name='phd'),
		url('', views.Admission.Fees, name='fees'),
		url('', views.Admission.FinancialAssistance, name='financialassist'),
		url('', views.Admission.Questions, name='question'),
		url('', views.Home.About, name='aboutt'),
        url('', views.Home.Mission, name='mission'),
		url('', views.Home.UpcomingCampus, name='campus'),
		url('', views.Home.Act, name='act'),
		url('', views.People.Faculty, name='faculty'),
		url('', views.People.AdjunctFaculty, name='adjfaculty'),
		url('', views.People.Btech, name='staff'),
		url('', views.People.Mtech, name='faculty'),
		url('', views.People.Phd, name='phdpeople'),
		url('', views.People.Alumni, name='alumni'),
		url('', views.Academics.Rulebook, name='rulebook'),
		url('', views.Academics.Departments, name='departments'),
		url('', views.Academics.Programmes, name='program'),
		url('', views.Academics.Convocation, name='convocation'),
		url('', views.Academics.Resources, name='resources'),
		url('', views.Academics.StudentVerification, name='verification'),
		url('', views.Research.Publications, name='publications'),
		url('', views.Research.ResearchAreas, name='researchareas'),
		url('', views.Research.Events, name='events'),
		url('', views.Research.FellowshipAwards, name='awards'),
		url('', views.Placement.Message, name='message'),
		url('', views.Placement.WhyRecruit, name='whyrecruit'),
		url('', views.Placement.Procedure, name='procedure'),
		url('', views.Placement.Statistics, name='statistics'),
		url('', views.Placement.Internships, name='internships'),
		url('', views.Placement.Recruiters, name='recruiters'),
		url('', views.Placement.Startups, name='startups'),
		url('', views.Placement.ContactTnP, name='contactTnp'),
		url('', views.Careers.FacultyRecruitment, name='facrecruit'),
		url('', views.Careers.FacultyRecruitment, name='staffrecruit'),
		url('', views.StudentAffairs.EventsNews, name='eventnews'),
		url('', views.StudentAffairs.Facilities, name='facilities'),
		url('', views.StudentAffairs.Hostels, name='hostels'),
		url('', views.StudentAffairs.StudentClubs, name='studentclubs'),
		url('', views.StudentAffairs.DisciplineGrievance, name='grievance'),
]
